[project]
name = "md2lineflex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "parkwestlabs", email = "281970052+parkwestlabs@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
